### ISSUE TITLE
SynthDef cannot be found on SuperCollider 3.11.0

### ISSUE THREAD

**Issue by kikoso** [pjagielski/punkt#2]
I have followed the steps on the README file, but I receive an error on SuperCollider 3.11.0

- Clone punkt and punkt_template
- Open punk_template in IntelliJ.
- Open SuperCollider 3.11.0, and open and run punkt.scd
- Run main.kt on IntelliJ

In IntelliJ, the project seems to be running nicely:

In SuperCollider, the following lines are dropped:

```
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef play1 not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef tb303 not found
FAILURE IN SERVER /s_new SynthDef not found
```

**Comment by pjagielski** [comment]
Yes, there are some issues with current punkt.scd - you can check [this reddit comment](https://www.reddit.com/r/Kotlin/comments/g12l51/sideproject_daft_punk_da_funk_quarantine_remix_in/fnggqpx/) for a workaround. I'll comment on this issue when I fix this.
Thanks!

**Comment by pjagielski** [comment]
@kikoso Hi, so I separated the SuperCollider server boot and synthdef files. You can now just boot the SC server and run [this script](https://raw.githubusercontent.com/pjagielski/punkt/master/src/main/resources/punkt-synths.scd). Can you check if it works for you now?

**Comment by kikoso** [comment]
Exactly same problem as before:

FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef play1 not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef tb303 not found
FAILURE IN SERVER /s_new SynthDef not found

**Comment by kikoso** [comment]
Ok, it works when I actually execute this section, as you mentioned in Reddit:

> Then you should execute second section - with SynthDefs - place the cursor on line 10 and press Ctrl+Enter again. In the post window you should see just "-> a SynthDef". The if you run Main.kt you should hear some sounds ;) Let me know if that helped!

This could probably be included in the README of the project

**Comment by pjagielski** [comment]
Hmmm that's strange, what error you get in post window when you try to load punkt-synths.scd in SuperCollider?

**Comment by kikoso** [comment]
As mentioned in the previous message, there is no error when performing that step. It is not clear on the README.md, it would be better to update it with that step.
