### ISSUE TITLE
Can't get it started

### ISSUE THREAD

**Issue by kindofwhat** [pjagielski/punkt#3]
Complete newb here:

I tried to install supercolider from the ppa on ubuntu 18.04. It installed SC 3.9.1, which might be outdated.

When running Main.kt it complained about not finding 2 syntdefs: play1 and tb303

Do I have to install 3.11 to have this running=

**Comment by kindofwhat** [comment]
Update: I tried to define the synths with https://raw.githubusercontent.com/pjagielski/punkt/master/src/main/resources/punkt-synths.scd but then it complains that the function freeSelf is not found

**Comment by pjagielski** [comment]
Hi, yes it might need SC 3.10+, I installed it from sources with: https://github.com/lvm/build-supercollider
As a workaround, I think you can change `doneAction: Done.freeSelf` to `doneAction: 2`, let me know if it helps..

**Comment by kindofwhat** [comment]
update: i installed 3.11, it works, I did not test the alternative solution ==> closed & thx for this awesome tool!!!!
